network:
  version: 2
  renderer: networkd
  ethernets:
    eth0:
      dhcp4: no
      addresses:
        - 10.1.255.103/24
      routes:
        - to: default
          via: 10.1.255.101
      nameservers:
          addresses: [10.1.255.103]