# Install docker to Ubundu and Centos
---
- hosts: app
  become: true
  gather_facts: true

  tasks:
##### Ubuntu ###################################################################################################################
# Adding Packages Installation Tasks
    - name: Ubuntu Install aptitude
      apt:
        name: aptitude
        state: latest
        update_cache: true
      when: 
        - ansible_facts['distribution'] == "Ubuntu"
        - ansible_facts['distribution_major_version'] == "22"

    - name: Ubuntu Install required system packages
      apt:
        pkg:
          - apt-transport-https
          - ca-certificates
          - curl
          - software-properties-common
        state: latest
        update_cache: true
      when: 
        - ansible_facts['distribution'] == "Ubuntu"
        - ansible_facts['distribution_major_version'] == "22"
# Adding Docker Installation Tasks
    - name: Ubuntu Add Docker GPG apt Key
      apt_key:
        url: https://download.docker.com/linux/ubuntu/gpg
        state: present
      when: 
        - ansible_facts['distribution'] == "Ubuntu"
        - ansible_facts['distribution_major_version'] == "22"

    - name: Ubuntu Add Docker Repository
      apt_repository:
        repo: deb https://download.docker.com/linux/ubuntu focal stable
        state: present
      when: 
        - ansible_facts['distribution'] == "Ubuntu"
        - ansible_facts['distribution_major_version'] == "22"

    - name: Ubuntu Update apt and install docker-ce
      apt:
        name: docker-ce
        state: latest
        update_cache: true
      when: 
        - ansible_facts['distribution'] == "Ubuntu"
        - ansible_facts['distribution_major_version'] == "22"
##### Ubuntu ###################################################################################################################

##### Centos ###################################################################################################################
# Install packages
    - name: Centos Install pre-requisite packages
      yum:
        name: "{{item}}"
        state: latest
      loop:
        - yum-utils
        - device-mapper-persistent-data
        - lvm2
      when: 
        - ansible_facts['distribution'] == "CentOS"
        - ansible_facts['distribution_major_version'] == "7"
# Adding Docker Installation Tasks    
    - name: Centos Add Docker repo
      get_url:
        url: https://download.docker.com/linux/centos/docker-ce.repo
        dest: /etc/yum.repos.d/docer-ce.repo
      when: 
        - ansible_facts['distribution'] == "CentOS"
        - ansible_facts['distribution_major_version'] == "7"
      
    - name: Centos Install Docker
      package:
        name: docker-ce
        state: latest
      when: 
        - ansible_facts['distribution'] == "CentOS"
        - ansible_facts['distribution_major_version'] == "7"

    - name: Centos Start Docker service
      service:
        name: docker
        state: started
        enabled: yes
      when: 
        - ansible_facts['distribution'] == "CentOS"
        - ansible_facts['distribution_major_version'] == "7"

    - name: Centos Add user vagrant to docker group
      user:
        name: vagrant
        groups: docker
        append: yes
      when: 
        - ansible_facts['distribution'] == "CentOS"
        - ansible_facts['distribution_major_version'] == "7"
##### Centos ###################################################################################################################
