apiVersion: apps/v1
kind: Deployment
metadata:
  name: mynginx
  namespace: dev
  labels:
    app: mynginx 
spec:
  replicas: 1
  selector:
    matchLabels:
      app: mynginx      
  template:
    metadata:
      labels:
        app: mynginx        
    spec:
      containers:
      - name: nginx
        image: nginx:1.14.2
        ports:
        - containerPort: 80

---
apiVersion: v1
kind: Service
metadata:
  name: mynginx-service
  namespace: dev
  labels:
    app: mynginx    
spec:
  type: ClusterIP
  ports:
    - port: 80
      targetPort: 80
      protocol: TCP
      name: http
  selector:
    app: mynginx