# dnsmasq ansible role
---
- name: Install dnsmasq
  package:
    name: dnsmasq
    state: present
    
- name: Set conf file
  template:
    src: dnsmasq.j2
    dest: /etc/dnsmasq.conf
    owner: root
    group: root
    mode: u=rw,g=r,o=r
  notify: restart dnsmasq
  
- name: Start dnsmasq service
  systemd:
    name: dnsmasq
    state: started
    daemon_reload: true
    enabled: true
    
    
    